# In this exercise you start out by having a list of names, and a list of majors.

# Your job is to create:

#    A list of dictionaries of students (ie: students = [{‘id’: 1,’name’: ‘Claus’, ‘major’: ‘Math’}]), created in a normal function that returns the result.

#    A Generator that “returns” a generator object. So the student is yield instead of returned.

# Both functions should do the same, but one returns a list and one a generator object.
# students = [{‘id’: 1,’name’: ‘Clasu’, ‘major’: ‘Math’}]
# The id could be generated by a counter or like in a loop.
# The Name should be found by randomly chosing a name from the names list
# The Major should be found by randomly chosing a major from the major list

import random

names = ['John', 'Corey', 'Adam', 'Steve', 'Rick', 'Thomas']
majors = ['Math', 'Engineering', 'CompSci', 'Arts', 'Business']

def students_list(num_students):
    student_list = []
    for i in range(num_students):
        id = i
        name = random.choice(names)
        major = random.choice(majors)
        student = {
            "id" : id,
            "name" : name,
            "major" : major
        }
        student_list.append(student)
    return student_list


def students_generator(student_list):
    length = len(student_list)
    for i in range(length):
        yield student_list[i]


# Create iterable dictionary of students
people_list = students_list(2)
print (people_list)


# Generate generator
people_gen = students_generator(people_list)
test = (i for i in people_gen)

# Step through generator and print steps
print(next(test))
print(next(test))

# Stop Iteration sets in
print(next(test))

	

(i for i in range(10))


(x ** 2 for x in range(10) if x % 2 == 0)
